### ISSUE TITLE
Blizzard - Multiple issues

### ISSUE THREAD

**Issue by alucarddelta** [steamcache/generic#61] opened 2018-11-07 03:23 UTC
### Describe the issue you are having
The Blizzard client is having issues with the bnet cache docker.

- Downloading the games slowly, about 3% of available network speed,
- Reporting false "HITS" in the logs when downloading into a clean directory/fresh install
- Doesn't appear retrieve the cached files. This is believed as the router appears to be reporting the same download speed as the client on cached games. More testing to be done to confirm.
- Lots of reported log errors (timeouts).

Other cache dockers (Steam and Origin) download at full network speeds (3.2mb/s). and caches the files downloaded and retrieved correctly. (Origin is also reporting false hits too when downloading fresh cache files, but not a major issue right now)

Using Ubuntu 18.10 with latest docker-ce and latest docker pulls.

Below is a Grafana parsing of the logs, the client download speed and disk usage.

<img width="312" alt="blizzard" src="https://user-images.githubusercontent.com/20882097/48107822-c6003000-e28c-11e8-94c5-3759a867db6e.png">

<img width="504" alt="bnetclient" src="https://user-images.githubusercontent.com/20882097/48107931-f5af3800-e28c-11e8-88a9-9b9916a39fae.png">

<img width="674" alt="disksize" src="https://user-images.githubusercontent.com/20882097/48108661-b7674800-e28f-11e8-8085-f1fc5f71ff1d.png">

### How are you running the container(s)?
```
Blizzard / Battle.net

docker run \
  --restart unless-stopped -d \
  --name blizzard-cache \
  -v /home/data/steamcache/blizzard/data:/data/cache \
  -v /home/data/steamcache/blizzard/logs:/data/logs \
  -p 192.168.1.212:80:80 \
  steamcache/generic:latest
```

### DNS Configuration
```
DNS

docker run \
  --restart unless-stopped -d \
  --name steamcache-dns \
  -p 192.168.1.210:53:53/udp \
  -e UPSTREAM_DNS=1.1.1.1 \
  -e STEAMCACHE_IP=192.168.1.210 \
  -e ORIGINCACHE_IP=192.168.1.211 \
  -e BLIZZARDCACHE_IP=192.168.1.212 \
  -e RIOTCACHE_IP=192.168.1.213 \
  -e FRONTIERCACHE_IP=192.168.1.214 \
  -e WSUSCACHE_IP=192.168.1.215 \
  steamcache/steamcache-dns:latest

HTTPS

docker run \
  --restart unless-stopped -d \
  --name sniproxy \
  -p 443:443 \
  steamcache/sniproxy:latest

```
### Output of container(s)

error.log tail
```
2018/11/07 02:54:06 [error] 20#20: *14622 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.120, server: , request: "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1", subrequest: "/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", upstream: "http://137.221.64.1:80/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", host: "us.cdn.blizzard.com"
2018/11/07 02:54:08 [error] 16#16: *14646 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.120, server: , request: "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1", subrequest: "/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", upstream: "http://137.221.64.4:80/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", host: "us.cdn.blizzard.com"
2018/11/07 02:54:10 [error] 14#14: *14473 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.120, server: , request: "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1", upstream: "http://137.221.64.4:80/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", host: "us.cdn.blizzard.com"
2018/11/07 02:54:11 [error] 15#15: *14552 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.120, server: , request: "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1", subrequest: "/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", upstream: "http://137.221.64.5:80/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", host: "us.cdn.blizzard.com"
2018/11/07 02:54:17 [error] 24#24: *14602 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.1.120, server: , request: "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1", upstream: "http://137.221.64.3:80/tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8", host: "us.cdn.blizzard.com"
```
Access.log tail
```
192.168.1.120 / - - - [07/Nov/2018:02:55:14 +0000] "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1" 206 266240 "-" "-" "HIT" "us.cdn.blizzard.com" "bytes=147858222-148124461"
192.168.1.120 / - - - [07/Nov/2018:02:55:15 +0000] "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1" 206 266240 "-" "-" "MISS" "level3.blizzard.com" "bytes=158507822-158774061"
192.168.1.120 / - - - [07/Nov/2018:02:55:15 +0000] "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1" 206 266240 "-" "-" "HIT" "level3.blizzard.com" "bytes=158774062-159040301"
192.168.1.120 / - - - [07/Nov/2018:02:55:15 +0000] "GET /tpr/ovw/data/44/3f/443f051f88353e3e42254de35a8ef8a8 HTTP/1.1" 206 266240 "-" "-" "HIT" "level3.blizzard.com" "bytes=159040302-159306541"
```

**Comment by sta3b** [comment] 2018-11-08 15:33
yep same issue my side too, already opened a thread about it and thanks for those details! :D

**Comment by alucarddelta** [comment] 2018-11-09 03:10
@sta3b Yah I saw, but cause I did it before I went to bed the other night, I miss read it as similar but not quite, So I raised a new issue.  Being fully awake now I can see that they are the same haha.

I know this used to work too around the time Blops4 beta was out. So its def a recent change.

**Comment by sta3b** [comment] 2018-12-08 19:05
@alucarddelta hello, the issue was with the ISP, i am getting these errors : 

2018/12/08 18:56:33 [error] 22#22: *122 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index HTTP/1.1", upstream: "http://95.101.114.18:80/tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index", host: "blzddist1-a.akamaihd.net"
2018/12/08 18:56:33 [error] 22#22: *122 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index HTTP/1.1", upstream: "http://95.101.114.26:80/tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index", host: "blzddist1-a.akamaihd.net"

the problem is with blzddist1-a.akamaihd.net (AKAMAI) , ISP will check it with them and should be resolved in a couple of days, will let you know
so you should be having the same issue with ur ISP, could be something other than AKAMAI

**Comment by VibroAxe** [comment] 2019-02-07 15:21
@sta3b did you get this resolved?

**Comment by sta3b** [comment] 2019-02-07 15:24
@vibroaxe yeah its resolved, added network cards to the server and each cache service is running on a separate network card

**Comment by VibroAxe** [comment] 2019-02-07 15:25
@sta3b you might find steamcache/monolithic useful. It's still relatively early in it's lifecycle but well battle tested. Saves needed multiple ips (obviously you lose the additional network cards bandwidth if you aren't LAGG though)

**Closed as completed by VibroAxe** 2019-02-07 15:25 UTC
